### ISSUE TITLE
无法响应

### ISSUE THREAD

**Issue by Z735803792** [NumberSir/nonebot_plugin_arktools#1]
如下图
用nb安装，python3.9.12,安装无任何报错，env.也写入有效路径，
终端无任何回应
![image](https://user-images.githubusercontent.com/70925546/170911555-d8f5bf89-a449-49e6-b347-edef09d0a764.png)
![image](https://user-images.githubusercontent.com/70925546/170911952-34322896-cf0d-43da-882d-702a5fb33e1e.png)
![image](https://user-images.githubusercontent.com/70925546/170911728-361d6ac2-0f3f-4125-b230-ed3921aa9a9d.png)
![image](https://user-images.githubusercontent.com/70925546/170911809-ff5994a3-22f0-4d77-9749-f5afd371a867.png)

**Comment by NumberSir** [comment]
已修复，请重新下载
