### ISSUE TITLE
公招识别读取头像图片路径的处理似乎有问题

### ISSUE THREAD

**Issue by Yangleis** [NumberSir/nonebot_plugin_arktools#11]
[v0.5.4]版本中
nonebot_plugin_arktools/open_recruitment/data_source.py中
第283行
`avatar = Image.open(Path().parent / "avatar" / f"{op[1]}.png").convert("RGBA").resize((128, 128))  # 头像`
获取到的是nonebot运行路径下的avatar目录，可能应该改为
`avatar = Image.open(Path(__file__).parent.parent / "_data" / "operator_info" / "image" / "avatar" / f"{op[1]}.png").convert("RGBA").resize((128, 128))  # 头像`
此处为插件安装的目录，与自动更新下载路径一致。

**Comment by liuzj288** [comment]
> [v0.5.4]版本中 nonebot_plugin_arktools/open_recruitment/data_source.py中 第283行 `avatar = Image.open(Path().parent / "avatar" / f"{op[1]}.png").convert("RGBA").resize((128, 128)) # 头像` 获取到的是nonebot运行路径下的avatar目录，可能应该改为 `avatar = Image.open(Path(__file__).parent.parent / "_data" / "operator_info" / "image" / "avatar" / f"{op[1]}.png").convert("RGBA").resize((128, 128)) # 头像` 此处为插件安装的目录，与自动更新下载路径一致。

确实，改了之后这个报错就解决了
![image](https://user-images.githubusercontent.com/13833404/190278875-e7499b83-61da-4c35-a6e7-d92149d82e07.png)

**Comment by NumberSir** [comment]
> > [v0.5.4]版本中 nonebot_plugin_arktools/open_recruitment/data_source.py中 第283行 `avatar = Image.open(Path().parent / "avatar" / f"{op[1]}.png").convert("RGBA").resize((128, 128)) # 头像` 获取到的是nonebot运行路径下的avatar目录，可能应该改为 `avatar = Image.open(Path(__file__).parent.parent / "_data" / "operator_info" / "image" / "avatar" / f"{op[1]}.png").convert("RGBA").resize((128, 128)) # 头像` 此处为插件安装的目录，与自动更新下载路径一致。
> 
> 确实，改了之后这个报错就解决了 ![image](https://user-images.githubusercontent.com/13833404/190278875-e7499b83-61da-4c35-a6e7-d92149d82e07.png)



> [v0.5.4]版本中 nonebot_plugin_arktools/open_recruitment/data_source.py中 第283行 `avatar = Image.open(Path().parent / "avatar" / f"{op[1]}.png").convert("RGBA").resize((128, 128)) # 头像` 获取到的是nonebot运行路径下的avatar目录，可能应该改为 `avatar = Image.open(Path(__file__).parent.parent / "_data" / "operator_info" / "image" / "avatar" / f"{op[1]}.png").convert("RGBA").resize((128, 128)) # 头像` 此处为插件安装的目录，与自动更新下载路径一致。

已修复
