### ISSUE TITLE
部分功能参考

### ISSUE THREAD

**Issue by Nenot233** [NumberSir/nonebot_plugin_arktools#12]
https://github.com/AmiyaBot/Amiya-Bot

**Comment by Nenot233** [comment]
https://www.amiya.cn/blog/function.html#%E6%9F%A5%E7%9C%8B%E9%98%BF%E7%B1%B3%E5%A8%85%E7%9A%84%E6%BA%90%E4%BB%A3%E7%A0%81

**Comment by Nenot233** [comment]
理智恢复提醒
合成玉计算
这两个挺好用的

**Comment by NumberSir** [comment]
> 理智恢复提醒 合成玉计算 这两个挺好用的

收到

**Comment by Nenot233** [comment]
![Uploading %TIGR]16UIA(CIUS_8]IXGG.jpg…]()
理智图可以参考这个
https://yituliu.site/

**Comment by Nenot233** [comment]
![%TIGR 16UIA(CIUS_8 IXGG](https://user-images.githubusercontent.com/108965579/198858621-92eabcd6-2645-4cb0-b50a-658f094eb0f5.jpg)
