### ISSUE TITLE
更新后报错

### ISSUE THREAD

**Issue by liuzj288** [NumberSir/nonebot_plugin_arktools#15]
![image](https://user-images.githubusercontent.com/13833404/192073097-d32303c0-94fc-4caa-92d9-442b0e0dc625.png)

**Comment by NumberSir** [comment]
已修复，请重新下载

**Comment by Yangleis** [comment]
[v0.5.7]版本依旧报错，问题不在于路径处理，之前的路径是对的。
报错是因为没使用过理智提醒不会创建这个问题，但是理智提醒的定时任务依旧会尝试读取这个文件，导致报错。
可以提前创建一个空文件，或者在定时任务中添加文件不存在的处理。
