### ISSUE TITLE
[v0.5.7]版本理智提醒功能文件不存在依旧报错

### ISSUE THREAD

**Issue by Yangleis** [NumberSir/nonebot_plugin_arktools#16]
[v0.5.7]版本依旧报错，问题不在于路径处理，之前的路径是对的。
        报错是因为没使用过理智提醒不会创建这个问题，但是理智提醒的定时任务依旧会尝试读取这个文件，导致报错。
        可以提前创建一个空文件，或者在定时任务中添加文件不存在的处理。

_Originally posted by @Yangleis in https://github.com/NumberSir/nonebot_plugin_arktools/issues/15#issuecomment-1256998493_

**Comment by Yangleis** [comment]
临时解决办法就是手动创建这个空文件就好了。

**Comment by NumberSir** [comment]
添加了文件不存在就不再尝试读取的判断，请更新
