### ISSUE TITLE
作图好像有点问题

### ISSUE THREAD

**Issue by Reinhard9396** [NumberSir/nonebot_plugin_arktools#18]
在只有一个tag有特殊（例如单个快活或者特种）的情况下会出现这种情况：
![image](https://user-images.githubusercontent.com/95238626/192155959-1c38bcf3-7830-4663-a8ea-92d9b3c34821.png)
看了下应该是作图时候出现的问题QAQ希望修一修捏

**Comment by NumberSir** [comment]
这是因为公招先前由手动输入标签改为了文字识别。
现在重新加回了手动输入标签，请更新插件

**Comment by Reinhard9396** [comment]
> 这是因为公招先前由手动输入标签改为了文字识别。 现在重新加回了手动输入标签，请更新插件

不是，我的意思是当tag组只有一个的时候会返回空的图片：
![2X5G(2HJ590@997GWTL4`D5](https://user-images.githubusercontent.com/95238626/192579482-77f33bfc-03ba-4edb-88d0-a48a6dd3d398.jpg)
但结果输出是正常的，所以我怀疑问题出在作图上：
![186YAQW OD5~($5W8V42CST](https://user-images.githubusercontent.com/95238626/192579859-860c1359-b2ce-419b-8bd5-35c3d61ec1c7.png)

如果有复数个tag组时作图是正常的：
![AH47SF~K7R8PSIMC@`3%$E7](https://user-images.githubusercontent.com/95238626/192580404-87271d0b-9d86-4b08-898c-49008104ca94.jpg)
