### ISSUE TITLE
特定组合触发bug了

### ISSUE THREAD

**Issue by liuzj288** [NumberSir/nonebot_plugin_arktools#19]
![image](https://user-images.githubusercontent.com/13833404/194105110-cf11c82e-686b-44d3-8706-96cac0c4976f.png)
![image](https://user-images.githubusercontent.com/13833404/194105247-e4346637-85f5-406a-8eb6-55fa67ce3f52.png)

**Comment by AdminVivy** [comment]
同样的，我把await去掉，以及给函数加上async虽然不会报错了；但是也会出现如此的bug
![image](https://user-images.githubusercontent.com/90098435/197764385-9da09ac1-ca16-4926-83bd-d0ba9493e6c6.png)
![LC3OYQ1 71VQI}HZBSBB4ZQ](https://user-images.githubusercontent.com/90098435/197764645-a11597de-7d06-450c-b0cb-a7f7017a666e.jpg)

**Comment by ghskyzhou** [comment]
同，好多tag都会触发这个（

**Comment by NumberSir** [comment]
> ![image](https://user-images.githubusercontent.com/13833404/194105110-cf11c82e-686b-44d3-8706-96cac0c4976f.png) ![image](https://user-images.githubusercontent.com/13833404/194105247-e4346637-85f5-406a-8eb6-55fa67ce3f52.png)



> 同样的，我把await去掉，以及给函数加上async虽然不会报错了；但是也会出现如此的bug ![image](https://user-images.githubusercontent.com/90098435/197764385-9da09ac1-ca16-4926-83bd-d0ba9493e6c6.png) ![LC3OYQ1 71VQI}HZBSBB4ZQ](https://user-images.githubusercontent.com/90098435/197764645-a11597de-7d06-450c-b0cb-a7f7017a666e.jpg)



> 同，好多tag都会触发这个（

已修复
