### ISSUE TITLE
文字公招报错

### ISSUE THREAD

**Issue by HL-Light** [NumberSir/nonebot_plugin_arktools#21]
目前进行文字公招后会提示“await“”无法使用[](url)

> Type Error: object list can't be used in ' await' expression

**Comment by ghskyzhou** [comment]
> 目前进行文字公招后会提示“await“”无法使用
> 
> > Type Error: object list can't be used in ' await' expression

把await删掉试试

**Comment by NumberSir** [comment]
> 目前进行文字公招后会提示“await“”无法使用
> 
> > Type Error: object list can't be used in ' await' expression



> > 目前进行文字公招后会提示“await“”无法使用
> > > Type Error: object list can't be used in ' await' expression
> 
> 把await删掉试试

已修复
