### ISSUE TITLE
部分功能无法被使用

### ISSUE THREAD

**Issue by Kreator33** [NumberSir/nonebot_plugin_arktools#22]
经尝试，只有指令"方舟今日资源"与"方舟最新活动"能够被事件响应器(Matcher)触发并让BOT回复，其他指令均无法触发事件相应器。
------------------------------------------------
![QQ截图20221111005728.97g8bQ1gY.png](https://api.onedrive.com/v1.0/shares/s!AhAGEbrlUqUbtwaXopAktm_BNLxv/root/content)
------------------------------------------------
![QQ截图20221111005946.IZKsS3Mp9g.png](https://api.onedrive.com/v1.0/shares/s!AhAGEbrlUqUbtwc-iXoJCACLhgyG/root/content)
------------------------------------------------
![QQ截图20221111005926.o8jFh6dRCE.png](https://api.onedrive.com/v1.0/shares/s!AhAGEbrlUqUbtwi6gZJkChxEAlCc/root/content)

**Comment by Kreator33** [comment]
已解决，在.env文件中添加 "COMMAND_START=[""]"

**Comment by ENE4546** [comment]
哇我也是这个问题，但是我.env文件中已经有了 "COMMAND_START=[""]"，还是只能触发那两个
