### ISSUE TITLE
启动报错，部分功能指令无响应 请求支援

### ISSUE THREAD

**Issue by sunyink** [NumberSir/nonebot_plugin_arktools#23]
您好，我最近给机器人添加arktools插件，但启动一直报错如下。py服务最终还是启动了，bot能处理返回`方舟今日资源`、`方舟最新活动`并可以进行`更新方舟游戏数据`，但对其他命令都无响应。
环境为服务系统win2012R2，py目前为python-3.10.8-amd64，运作在云崽的py-plugin上，另外的几个插件可以正常加载。
我尝试重装插件、更新py都没办法解决，望能麻烦指点一下，谢谢  (￣.￣)

> [报错log如下]===============================================

[PyBot][08:08:47.044][ERROR] [plugin.manager]插件导入失败： "nonebot_plugin_arkt
ools"
Traceback (most recent call last):
  File "C:\ServerBot\serverbot\git\Yunzai-Bot\plugins\py-plugin\main.py", line 1
3, in <module>
    nonebot.run(root)
  File "C:\ServerBot\serverbot\git\Yunzai-Bot\plugins\py-plugin\nonebot\__init__
.py", line 56, in run
    _driver.run([str(x) for x in _driver.config.plugins])
  File "C:\ServerBot\serverbot\git\Yunzai-Bot\plugins\py-plugin\nonebot\drivers.
py", line 48, in run
    loop.run_until_complete(self.serve(plugins))
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python310\lib\async
io\base_events.py", line 636, in run_until_complete
    self.run_forever()
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python310\lib\async
io\windows_events.py", line 321, in run_forever
    super().run_forever()
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python310\lib\async
io\base_events.py", line 603, in run_forever
    self._run_once()
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python310\lib\async
io\base_events.py", line 1899, in _run_once
    handle._run()
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python310\lib\async
io\events.py", line 80, in _run
    self._context.run(self._callback, *self._args)
  File "C:\ServerBot\serverbot\git\Yunzai-Bot\plugins\py-plugin\nonebot\drivers.
py", line 62, in serve
    load_plugin(plugin.replace("-", "_"))
  File "C:\ServerBot\serverbot\git\Yunzai-Bot\plugins\py-plugin\nonebot\plugin\l
oad.py", line 34, in load_plugin
    return manager.load_plugin(module_path)
 File "C:\ServerBot\serverbot\git\Yunzai-Bot\plugins\py-plugin\nonebot\plugin\m
anager.py", line 141, in load_plugin
    module = importlib.import_module(name)
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python310\lib\impor
tlib\__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1050, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1027, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1006, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 688, in _load_unlocked
  File "C:\ServerBot\serverbot\git\Yunzai-Bot\plugins\py-plugin\nonebot\plugin\m
anager.py", line 233, in exec_module
    super().exec_module(module)
  File "<frozen importlib._bootstrap_external>", line 883, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "C:\Users\Administrator\AppData\Local\pypoetry\Cache\virtualenvs\py-plugi
n-1Na8YC3r-py3.10\lib\site-packages\nonebot_plugin_arktools\__init__.py", line 3
, in <module>
    from .open_recruitment import *
  File "C:\Users\Administrator\AppData\Local\pypoetry\Cache\virtualenvs\py-plugi
n-1Na8YC3r-py3.10\lib\site-packages\nonebot_plugin_arktools\open_recruitment\__i
nit__.py", line 7, in <module>
    from .data_source import ocr, get_rare_operators, build_image, process_word_
tags
  File "C:\Users\Administrator\AppData\Local\pypoetry\Cache\virtualenvs\py-plugi
n-1Na8YC3r-py3.10\lib\site-packages\nonebot_plugin_arktools\open_recruitment\dat
a_source.py", line 17, in <module>
    recruit_config = Config.parse_obj(get_driver().config.dict())
  File "pydantic\main.py", line 521, in pydantic.main.BaseModel.parse_obj
    return cls(**obj)
  File "pydantic\main.py", line 341, in pydantic.main.BaseModel.__init__
    raise validation_error
pydantic.error_wrappers.ValidationError: 2 validation errors for Config
tencent_cloud_secret_id
  field required (type=value_error.missing)
tencent_cloud_secret_key
  field required (type=value_error.missing)

> [log end]======================================

**Comment by Mulsd** [comment]
应该是没有配置变量

**Comment by SyuviDorra** [comment]
> 

你好大佬我也遇到了这个问题，请问要怎么配置变量呢

**Comment by SyuviDorra** [comment]
> > 你好大佬我也遇到了这个问题，请问要怎么配置变量呢
> > 主页有的...填写evn文件
> 
> ```
> daily_levels_path="xxx"     # 每日资源关卡的截图文件在本地存储的路径
> activities_img_path="xxx"   # 新活动的截图文件在本地存储的路径
> activities_data_path="xxx"  # 新活动的数据文件在本地存储的路径
> operator_save_path="xxx"    # 干员信息查询生成的图片文件在本地存储的路径
> tencent_cloud_secret_id="xxx"  # 腾讯云开发者 SecretId，这两项在 https://console.cloud.tencent.com/cam/capi 可以创建并查询
> tencent_cloud_secret_key="xxx"  # 腾讯云开发者 SecretKey，另需开通 OCR 服务，见 https://console.cloud.tencent.com/ocr/overview
> recruitment_save_path="xxx"  # 公招查询结果图片缓存路径
> ...
> ```

哦哦，好的，谢谢大佬

**Comment by SyuviDorra** [comment]
> > 你好大佬我也遇到了这个问题，请问要怎么配置变量呢
> > 主页有的...填写evn文件
> 
> ```
> daily_levels_path="xxx"     # 每日资源关卡的截图文件在本地存储的路径
> activities_img_path="xxx"   # 新活动的截图文件在本地存储的路径
> activities_data_path="xxx"  # 新活动的数据文件在本地存储的路径
> operator_save_path="xxx"    # 干员信息查询生成的图片文件在本地存储的路径
> tencent_cloud_secret_id="xxx"  # 腾讯云开发者 SecretId，这两项在 https://console.cloud.tencent.com/cam/capi 可以创建并查询
> tencent_cloud_secret_key="xxx"  # 腾讯云开发者 SecretKey，另需开通 OCR 服务，见 https://console.cloud.tencent.com/ocr/overview
> recruitment_save_path="xxx"  # 公招查询结果图片缓存路径
> ...
> ```

抱歉大佬，问一个可能很笨的问题，请问这个evn文件是在哪里，我搜了一下好像没找到qwq

**Comment by Mulsd** [comment]
这。。
我是指用nb生成的机器人根目录里以evn（应该是这个）开头的几个文件，全部填了

**Comment by SyuviDorra** [comment]
> 这。。 我是指用nb生成的机器人根目录里以evn（应该是这个）开头的几个文件，全部填了

谢谢大佬，解决了，我是在Windows上用pip指令安装的，我找了一下是config文件

**Comment by SyuviDorra** [comment]
> 这。。 我是指用nb生成的机器人根目录里以evn（应该是这个）开头的几个文件，全部填了

啊，填完现在虽然没有报错了，但是干员和公招指令发送还是没有反应qwq，而且日志处没有报错，就好像发送的不是指令一样

**Comment by SyuviDorra** [comment]
> 这。。 我是指用nb生成的机器人根目录里以evn（应该是这个）开头的几个文件，全部填了

啊哈哈是我智障了，忘记加/号了，抱歉打扰大佬你了

**Comment by sunyink** [comment]
我参考二位的线索，又研究了半天。觉得py的脚本目录怎么有好几个，比如`C:\Users\Administrator\AppData\Local\pypoetry\Cache\virtualenvs\py-plugin-1Na8YC3r-py3.10\Lib\site-packages\nonebot_plugin_arktools`和`C:\ServerBot\serverbot\git\Yunzai-Bot\plugins\py-plugin\nonebot`下都有“nonebot_plugin_arktools”插件的东西，好像命令素材图自动下载都下到`C:\Users\Administrator\AppData\Local\pypoetry\Cache\virtualenvs\py-plugin-1Na8YC3r-py3.10\Lib\site-packages\nonebot_plugin_arktools`里面，但活动、每日素材在`C:\ServerBot\serverbot\git\Yunzai-Bot\plugins\py-plugin\nonebot`下都有“nonebot_plugin_arktools”。硬着头皮看报错，发现“pypoetry\Cache"里比仓库还少东西，git clone了一下，又点歌和手动公招会报错直接py崩溃重启。

实在搞不懂2个目录分别干嘛的？
我这么尝试了下变量，api我先跳过了。yaml好像格式还不一样，我照猫画虎改了下。
`daily_levels_path: /data/arktools/daily_source
activities_img_path: /ServerBot/serverbot/git/Yunzai-Bot/plugins/py-plugin/data/arktools/activity/img
activities_data_path: /data/arktools/activity/data
operator_save_path: /data/arktools/activity/data
tencent_cloud_secret_id: "000000"
tencent_cloud_secret_key: "000000"
recruitment_save_path: /data/arktools/activity/data`

**Comment by Mulsd** [comment]
> 我参考二位的线索，又研究了半天。觉得py的脚本目录怎么有好几个，比如
>......
>```
> recruitment_save_path: /data/arktools/activity/data
> ```

你的机器人有没有成功运行了？
我去读了一下云崽py插件的说明，你不妨去试一下[第五点](https://gitee.com/realhuhu/py-plugin#5%E4%BD%BF%E7%94%A8%E8%BF%9C%E7%A8%8B)里面写的方法远程使用这个插件

**Comment by NumberSir** [comment]
> 您好，我最近给机器人添加arktools插件，但启动一直报错如下。py服务最终还是启动了，bot能处理返回`方舟今日资源`、`方舟最新活动`并可以进行`更新方舟游戏数据`，但对其他命令都无响应。 环境为服务系统win2012R2，py目前为python-3.10.8-amd64，运作在云崽的py-plugin上，另外的几个插件可以正常加载。 我尝试重装插件、更新py都没办法解决，望能麻烦指点一下，谢谢 (￣.￣)
> 
> > [报错log如下]===============================================
> 
> [PyBot][08:08:47.044][ERROR] [plugin.manager]插件导入失败： "nonebot_plugin_arkt ools" Traceback (most recent call last): File "C:\ServerBot\serverbot\git\Yunzai-Bot\plugins\py-plugin\main.py", line 1 3, in nonebot.run(root) File "C:\ServerBot\serverbot\git\Yunzai-Bot\plugins\py-plugin\nonebot__init__ .py", line 56, in run _driver.run([str(x) for x in _driver.config.plugins]) File "C:\ServerBot\serverbot\git\Yunzai-Bot\plugins\py-plugin\nonebot\drivers. py", line 48, in run loop.run_until_complete(self.serve(plugins)) File "C:\Users\Administrator\AppData\Local\Programs\Python\Python310\lib\async io\base_events.py", line 636, in run_until_complete self.run_forever() File "C:\Users\Administrator\AppData\Local\Programs\Python\Python310\lib\async io\windows_events.py", line 321, in run_forever super().run_forever() File "C:\Users\Administrator\AppData\Local\Programs\Python\Python310\lib\async io\base_events.py", line 603, in run_forever self._run_once() File "C:\Users\Administrator\AppData\Local\Programs\Python\Python310\lib\async io\base_events.py", line 1899, in _run_once handle._run() File "C:\Users\Administrator\AppData\Local\Programs\Python\Python310\lib\async io\events.py", line 80, in _run self._context.run(self._callback, *self._args) File "C:\ServerBot\serverbot\git\Yunzai-Bot\plugins\py-plugin\nonebot\drivers. py", line 62, in serve load_plugin(plugin.replace("-", "_")) File "C:\ServerBot\serverbot\git\Yunzai-Bot\plugins\py-plugin\nonebot\plugin\l oad.py", line 34, in load_plugin return manager.load_plugin(module_path) File "C:\ServerBot\serverbot\git\Yunzai-Bot\plugins\py-plugin\nonebot\plugin\m anager.py", line 141, in load_plugin module = importlib.import_module(name) File "C:\Users\Administrator\AppData\Local\Programs\Python\Python310\lib\impor tlib__init__.py", line 126, in import_module return _bootstrap._gcd_import(name[level:], package, level) File "", line 1050, in _gcd_import File "", line 1027, in _find_and_load File "", line 1006, in _find_and_load_unlocked File "", line 688, in _load_unlocked File "C:\ServerBot\serverbot\git\Yunzai-Bot\plugins\py-plugin\nonebot\plugin\m anager.py", line 233, in exec_module super().exec_module(module) File "", line 883, in exec_module File "", line 241, in _call_with_frames_removed File "C:\Users\Administrator\AppData\Local\pypoetry\Cache\virtualenvs\py-plugi n-1Na8YC3r-py3.10\lib\site-packages\nonebot_plugin_arktools__init__.py", line 3 , in from .open_recruitment import * File "C:\Users\Administrator\AppData\Local\pypoetry\Cache\virtualenvs\py-plugi n-1Na8YC3r-py3.10\lib\site-packages\nonebot_plugin_arktools\open_recruitment__i nit__.py", line 7, in from .data_source import ocr, get_rare_operators, build_image, process_word tags File "C:\Users\Administrator\AppData\Local\pypoetry\Cache\virtualenvs\py-plugi n-1Na8YC3r-py3.10\lib\site-packages\nonebot_plugin_arktools\open_recruitment\dat a_source.py", line 17, in recruit_config = Config.parse_obj(get_driver().config.dict()) File "pydantic\main.py", line 521, in pydantic.main.BaseModel.parse_obj return cls(**obj) File "pydantic\main.py", line 341, in pydantic.main.BaseModel.**init** raise validation_error pydantic.error_wrappers.ValidationError: 2 validation errors for Config tencent_cloud_secret_id field required (type=value_error.missing) tencent_cloud_secret_key field required (type=value_error.missing)_
> 
> > [log end]======================================

> > 
> 
> 你好大佬我也遇到了这个问题，请问要怎么配置变量呢

请重新下载最新版本
