### ISSUE TITLE
更新后报错，似乎是网址手滑了，我没定位到文件

### ISSUE THREAD

**Issue by liuzj288** [NumberSir/nonebot_plugin_arktools#26]
![image](https://user-images.githubusercontent.com/13833404/218370811-07616628-3aa3-4ff4-a140-d5a82421e0a3.png)

**Comment by NumberSir** [comment]
> ![image](https://user-images.githubusercontent.com/13833404/218370811-07616628-3aa3-4ff4-a140-d5a82421e0a3.png)

已修复，现在默认使用 https://raw.githubusercontent.com，可在 .env.env 中修改
