### ISSUE TITLE
无法读取资源

### ISSUE THREAD

**Issue by ykinsoul** [NumberSir/nonebot_plugin_arktools#28]
使用指令“更新方舟素材”可得到“正在更新素材”回应，但无“素材更新完成”回应，且查询干员时大部分干员会报错
![image](https://user-images.githubusercontent.com/71212242/219283013-a93d135a-eb64-4f0a-898a-2ab3e5aa9861.png)
![image](https://user-images.githubusercontent.com/71212242/219283249-986b793f-db3d-4273-a80b-f3afdf8b8990.png)

错误信息提及的目录及文件皆存在，且文件未损坏

运行环境windows server 2022, python 3.10

部署时使用了指令 `nb plugin install nonebot-plugin-arktools`

**Comment by jokergss** [comment]
同样遇到此问题，文件全部下载到正确位置但无法读取，且部分测试中不能返回信息
