### ISSUE TITLE
无法获取公告

### ISSUE THREAD

**Issue by ShanShuWu** [NumberSir/nonebot_plugin_arktools#30]
![image](https://user-images.githubusercontent.com/112482297/219852693-deb9912e-c2e5-4988-bd3f-c2af56c8c7db.png)，如图所示，不知道需不需要挂代理，不过另一方面频繁的尝试获取公告会卡住正在请求的指令，请问有方法关闭获取最新公告功能吗

**Comment by NumberSir** [comment]
> ![image](https://user-images.githubusercontent.com/112482297/219852693-deb9912e-c2e5-4988-bd3f-c2af56c8c7db.png)，如图所示，不知道需不需要挂代理，不过另一方面频繁的尝试获取公告会卡住正在请求的指令，请问有方法关闭获取最新公告功能吗

已添加禁用自动检测的配置，请更新
