### ISSUE TITLE
子功能能否加个开关，不改代码的话这个一直报错霸屏

### ISSUE THREAD

**Issue by liuzj288** [NumberSir/nonebot_plugin_arktools#33]
![image](https://user-images.githubusercontent.com/13833404/219945522-68724e50-2003-4f99-9246-919634eb78b1.png)

**Comment by NumberSir** [comment]
![image](https://user-images.githubusercontent.com/52584526/219946916-14b7cde0-8c3e-49b9-bd40-a8fc02b76759.png)

已加，qinggengx请更新至 v1.0.9
