### ISSUE TITLE
公招指令中，除了"公招"之外的关键词不会被进行文本处理

### ISSUE THREAD

**Issue by Kreator33** [NumberSir/nonebot_plugin_arktools#35]
https://github.com/NumberSir/nonebot_plugin_arktools/blob/7d26f8d915fe320ed65581d62e9097ced0461a83/nonebot_plugin_arktools/src/tool_open_recruitment/__init__.py#L16
https://github.com/NumberSir/nonebot_plugin_arktools/blob/7d26f8d915fe320ed65581d62e9097ced0461a83/nonebot_plugin_arktools/src/tool_open_recruitment/__init__.py#L31
https://github.com/NumberSir/nonebot_plugin_arktools/blob/7d26f8d915fe320ed65581d62e9097ced0461a83/nonebot_plugin_arktools/src/tool_open_recruitment/__init__.py#L32
代码中只会对"公招"进行替换处理
![QQ图片20230306165353.Is8KFT9xM.jpg](https://api.onedrive.com/v1.0/shares/s!AhAGEbrlUqUbt0ELlDXUu9hwrO2-/root/content)]

---

尝试对其稍微改动，目前能够正常运行.
![code.scQSf-jLG.png](https://api.onedrive.com/v1.0/shares/s!AhAGEbrlUqUbt0L-kM8WKfTMGTJ2/root/content)

**Comment by NumberSir** [comment]
已修复
