### ISSUE TITLE
【bug?】更新pypi版本会导致data消失

### ISSUE THREAD

**Issue by Umamusume-Agnes-Digital** [NumberSir/nonebot_plugin_arktools#36]
因为data是在包里面，这会导致每次更新pypi版本就要重新下一次300多M的素材，希望这个目录可以bot下的目录，例如bot.py所在目录下data/nonebot_plugin_arktools/，这样就不会因为更新版本而需要重新下载素材包了。

**Comment by NumberSir** [comment]
已添加配置项，现在默认在根目录下
