### ISSUE TITLE
资源下载失败

### ISSUE THREAD

**Issue by muyun618** [NumberSir/nonebot_plugin_arktools#41]
图片资源自动下载失败，手动下要怎么下啊，找不到资源包QAQ

**Comment by NumberSir** [comment]
![S30424-17242540(1)](https://user-images.githubusercontent.com/52584526/233956234-eb77e715-0c1c-4e44-981b-b112f7bdf397.jpg)


> 图片资源自动下载失败，手动下要怎么下啊，找不到资源包QAQ
