### ISSUE TITLE
无法正常使用数据库

### ISSUE THREAD

**Issue by jeffxzy** [NumberSir/nonebot_plugin_arktools#42]
启动bot时，报错：
![image](https://user-images.githubusercontent.com/55473481/235976402-d7ec4c67-e1a2-42a9-81ca-3af53d1d6be7.png)

如果试图使用指令手动更新数据库：
![image](https://user-images.githubusercontent.com/55473481/235976765-b72a6ea0-93dc-4be0-8a1e-028870071c24.png)

如果试图调用猜干员：
![image](https://user-images.githubusercontent.com/55473481/235976926-9a9dcb0a-0101-40fe-94a4-34798ff696a2.png)

事实上，在四月中旬10日左右使用该插件时，没有遇到这一问题。在4月23日左右试图更新数据库时，第一次遇到这个问题（不能更新数据库），但是还可以正常使用功能。刚刚更新插件到最新版本后，该问题更严重至完全无法使用插件。
随后，试图下载data.zip，并解包到正确位置。结果如下：
![image](https://user-images.githubusercontent.com/55473481/235980361-17355bbc-b5eb-43b4-8248-96e0736133b5.png)
![image](https://user-images.githubusercontent.com/55473481/235980428-be27470f-d364-44b7-9ec2-93a5cbe4856f.png)

**Comment by NumberSir** [comment]
鹰角改数据格式了，正在修

**Comment by NumberSir** [comment]
已修复，请更新至v1.2.0
