### ISSUE TITLE
KeyError: 'specializeLevelUpData'

### ISSUE THREAD

**Issue by Kreator33** [NumberSir/nonebot_plugin_arktools#43]
在查询干员信息时会出现该问题.
![OZ}(PH}IAAVCKS5ZO{0K~R5](https://github.com/NumberSir/nonebot_plugin_arktools/assets/117357279/2f8d4fee-0483-4af2-bde1-80113cd74e35)

**Comment by NumberSir** [comment]
请用 `更新方舟数据库 -D` 命令重写数据库

**Comment by Kreator33** [comment]
已解决！

**Comment by Nenot233** [comment]
更新方舟数据库 -D 命令重写数据库还是会出现KeyError: 'specializeLevelUpData'

**Comment by Akejyo** [comment]
> 更新方舟数据库 -D 命令重写数据库还是会出现KeyError: 'specializeLevelUpData'

定位到 models_v3.py 里1234行，把 specializeLevelUpData 替换成 levelUpCostCond就行了
