### ISSUE TITLE
  公招不妨调用百度ocr

### ISSUE THREAD

**Issue by liuzj288** [NumberSir/nonebot_plugin_arktools#6]
像amiya-bot一样自动识图推荐
![image](https://user-images.githubusercontent.com/13833404/187544077-8a4b8447-cec9-43dd-89c1-752c3e09aa43.png)

**Comment by NumberSir** [comment]
百度OCR似乎没有免费额度，因此选用了腾讯OCR

**Comment by liuzj288** [comment]
> 

 这个的申请地址是啥

**Comment by liuzj288** [comment]
![image](https://user-images.githubusercontent.com/13833404/187770991-a5b1c323-d3a6-4657-9879-c2492cb8a64f.png)
运行失败

**Comment by NumberSir** [comment]
API申请地址在 https://console.cloud.tencent.com/cam/capi
OCR服务开通地址在 https://console.cloud.tencent.com/ocr/overview
三个缺少的文件我单独上传了，下载并放入 nonebot_plugin_arktools\_data\operator_info\json 文件夹中就好

**Comment by liuzj288** [comment]
> 并放入 nonebot_plugin_arktools_data\operator_info\js

怎么还是报错
![image](https://user-images.githubusercontent.com/13833404/187937097-3d17e235-a74d-4e5a-b25c-9f11633c8093.png)

**Comment by moyuguguji** [comment]
![QQ截图20220902032816](https://user-images.githubusercontent.com/108826874/187996667-29eed51f-db39-4513-8980-707287bc417d.png)
非常奇怪的解决方式,把这三个文件放bot根目录就解决了.......

**Comment by liuzj288** [comment]
> ![QQ截图20220902032816](https://user-images.githubusercontent.com/108826874/187996667-29eed51f-db39-4513-8980-707287bc417d.png) 非常奇怪的解决方式,把这三个文件放bot根目录就解决了.......

相对目录写的有问题吧，./默认就bot的根目录
