### ISSUE TITLE
ValidationError: 2 validation errors for Config

### ISSUE THREAD

**Issue by Nenot233** [NumberSir/nonebot_plugin_arktools#7]
raise validation_error
pydantic.error_wrappers.ValidationError: 2 validation errors for Config
tencent_cloud_secret_id
  field required (type=value_error.missing)
tencent_cloud_secret_key
  field required (type=value_error.missing)

SecretId: "id"
SecretKey: "key"

请问一下这个是格式问题还是腾讯apikey的问题？

**Comment by NumberSir** [comment]
![OGR@9JB6O%4 6U2DZC044%L](https://user-images.githubusercontent.com/52584526/187828818-eac7ae09-34b1-42ba-bf03-05898578285b.png)
腾讯云 API 密钥能在这个页面找到：https://console.cloud.tencent.com/cam/capi
两个都是字符串格式，看看你有没有填对

**Comment by Nenot233** [comment]
![image](https://user-images.githubusercontent.com/108965579/187829232-e4ddb1b6-e555-4a90-a3e3-679015964c4d.png)
均为复制上去的

**Comment by NumberSir** [comment]
你怎么填在这里，一般填在env.env文件里
如果填在这里的话用等号不用冒号
