### ISSUE TITLE
使用nb-cli安装的插件有几个目录缺失

### ISSUE THREAD

**Issue by Yangleis** [NumberSir/nonebot_plugin_arktools#8]
`
(nonebot-py3.10) ➜  nonebot_plugin_arktools ls
activity_notice  ark_daily_source  _exceptions  __init__.py  open_recruitment  operator_info  __pycache__  _utils
`
缺少_data、_api目录，导致运行时报错。

**Comment by Euterpe-lamiao** [comment]
在使用干员查询功能时也会缺少文件，在整个安装目录中查询不到该文件位置。

  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python39\lib\site-packages\nonebot_plugin_arktools\operator_info\data_source.py", line 41, in _get_operator_basic_info
    with open(JSON_PATH / "character_table.json", "r", encoding="utf-8") as f:
FileNotFoundError: [Errno 2] No such file or directory: 'C:\\Users\\Administrator\\AppData\\Local\\Programs\\Python\\Python39\\lib\\site-packages\\nonebot_plugin_arktools\\_data\\operator_info\\json\\character_table.json'

**Comment by NumberSir** [comment]
> `(nonebot-py3.10) ➜ nonebot_plugin_arktools ls activity_notice ark_daily_source _exceptions __init__.py open_recruitment operator_info __pycache__ _utils` 缺少_data、_api目录，导致运行时报错。



> 在使用干员查询功能时也会缺少文件，在整个安装目录中查询不到该文件位置。
> 
> File "C:\Users\Administrator\AppData\Local\Programs\Python\Python39\lib\site-packages\nonebot_plugin_arktools\operator_info\data_source.py", line 41, in _get_operator_basic_info with open(JSON_PATH / "character_table.json", "r", encoding="utf-8") as f: FileNotFoundError: [Errno 2] No such file or directory: 'C:\Users\Administrator\AppData\Local\Programs\Python\Python39\lib\site-packages\nonebot_plugin_arktools\_data\operator_info\json\character_table.json'

已更新资源获取方式为在线下载，请更新插件
